### ISSUE TITLE
nano-python to list all wallet?

### ISSUE THREAD

**Issue by lonnieOST** [dourvaris/nano-python#10]
Hello, 

I have just come across your nano-python library and I see that you can list all accounts within a wallet.
I am wondering if there is a way to list all wallets on the node server?

Cheers,

**Comment by Laurentiu-Andronache** [comment]
That's not possible through RPC: https://github.com/nanocurrency/nano-node/wiki/RPC-protocol

It's only possible with the command line interface: https://github.com/nanocurrency/nano-node/wiki/Command-line-interface

Use `nano_node --wallet_list` to do it!
