### ISSUE TITLE
Able to connect to rai_node via curl but not via RPCClient

### ISSUE THREAD

**Issue by pramttl** [dourvaris/nano-python#7]
Used this:
```
from raiblocks.rpc import RPCClient
rpc = RPCClient('http://127.0.0.1:7076')
rpc.version()
```
Got this error:
```
requests.exceptions.ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=7076): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc49d23d890>: Failed to establish a new connection: [Errno 111] Connection refused',))
```

But, the following command via CURL completes successfully -
```
curl -g -d '{ "action": "block_count" }' '[::1]:7076'
```

If curl works that implies RPC HTTP calls to the rai_node are working. Unable to figure out why the `requests.exceptions.ConnectionError`. Both the curl call and the python lib usage is done from the same instance so shouldn't be a firewall issue.

**Comment by pramttl** [comment]
Strange when I changed my rpc address from `::1` to `::ffff:127.0.0.1`, and restarted the `rai_node` then the connection via the python lib worked. `rai.version()` returned the version `{u'rpc_version': 1, u'node_vendor': u'RaiBlocks 9.0', u'store_version': 10}`

Confused because `::1` also refers to loopback/localhost in ipv6. So why would this change to `::ffff:127.0.0.1` make a difference ? Maybe, I'm missing something about IPv6.

**Comment by JamesBingo** [comment]
I had the same issue running the rai_node using the docker build.

**Comment by dourvaris** [comment]
It may probably be because `127.0.0.1` refers to the ipv4 localhost, does passing `http://localhost:7076` work with `::1`?
